// Generated by the build script. Do not edit directly!

pub static CATEGORIES: ::phf::Map<&'static str, Category> = ::phf::Map {
    key: 6988065091549448246,
    disps: ::phf::Slice::Static(&[
        (1, 0),
        (4, 10),
        (1, 10),
    ]),
    entries: ::phf::Slice::Static(&[
        ("Video", Category { kind: Kind::Main { requires: &["AudioVideo"] }, deprecated: false }),
        ("Development", Category { kind: Kind::Main { requires: &[] }, deprecated: false }),
        ("Network", Category { kind: Kind::Main { requires: &[] }, deprecated: false }),
        ("Utility", Category { kind: Kind::Main { requires: &[] }, deprecated: false }),
        ("Audio", Category { kind: Kind::Main { requires: &["AudioVideo"] }, deprecated: false }),
        ("Game", Category { kind: Kind::Main { requires: &[] }, deprecated: false }),
        ("AudioVideo", Category { kind: Kind::Main { requires: &[] }, deprecated: false }),
        ("Office", Category { kind: Kind::Main { requires: &[] }, deprecated: false }),
        ("System", Category { kind: Kind::Main { requires: &[] }, deprecated: false }),
        ("Graphics", Category { kind: Kind::Main { requires: &[] }, deprecated: false }),
        ("Education", Category { kind: Kind::Main { requires: &[] }, deprecated: false }),
        ("Settings", Category { kind: Kind::Main { requires: &[] }, deprecated: false }),
        ("Science", Category { kind: Kind::Main { requires: &[] }, deprecated: false }),
    ]),
};
